# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rusong?serverTimezone=UTC&useSSL=false&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zzw5730219